name: nestjs-tutorial

services:
  nest-db:
    image: postgres
    container_name: nest-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    restart: always
    volumes:
      - nestjs-tutorial-data:/var/lib/postgresql
    networks:
      - nestjs-tutorial-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "postgres" ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 10s

  nest-migration:
    build:
      context: .
      dockerfile: Dockerfile
      target: migration
    container_name: nest-migration
    depends_on:
      nest-db:
        condition: service_healthy
    env_file:
      - .env.production
    networks:
      - nestjs-tutorial-network

  nest-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    env_file:
      - .env.production
    ports:
      - '3000:3000'
    depends_on:
      - nest-db
    networks:
      - nestjs-tutorial-network

networks:
  nestjs-tutorial-network:


volumes:
  nestjs-tutorial-data:
