name: nestjs-tutorial

services:
  dev-db:
    image: postgres
    container_name: nest-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    restart: always
    networks:
      - nestjs-tutorial-network

networks:
  nestjs-tutorial-network:
